# Generated by Django 4.1.4 on 2022-12-18 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0001_initial"),
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.discount",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booking.seat"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="showtime",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cinema.showtime"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booking.tickettype"
            ),
        ),
    ]
